version: '3'
services:
  mysql:
    image: mysql:8 # 使用的镜像
    container_name: oj-mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # root 用户密码
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - mynetwork # 指定网络

  yuoj-backend-user-service:
    container_name: yuoj-backend-user-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "50000:50000"
    networks:
      - mynetwork
    depends_on:
      - oj-mysql
networks:
  mynetwork:
